FROM rocker/tidyverse:3.6.3

RUN apt-get update -qq && apt-get -y install \
apt-utils \
libv8-dev \
libjq-dev \
libjpeg-dev \
libprotobuf-dev \
protobuf-compiler \
libudunits2-dev \
libgeos++-dev \
libgdal-dev \
lbzip2 \
libproj-dev \
libnetcdf-dev \
netcdf-bin \
postgis \
libhdf5-dev \
libsqlite3-dev 
