#!/bin/bash -x
#SBATCH --partition=compute

SINGULARITY_IMAGE=$1
MOUNT_DATA=$2
MOUNT_DATA_PROJECT=$3
MONICA_OUT=$4
WORKDIR=$5
SCRIPT=$6
shift 6
ADDITIONAL_PARAMETER=$@

DATA=/data
OUT=/out
PROJECT=/project

cd $WORKDIR
singularity run -B \
$MOUNT_DATA:$DATA,\
$MOUNT_DATA_PROJECT:$PROJECT,\
$MONICA_OUT:$OUT \
${SINGULARITY_IMAGE} python ${SCRIPT} ${ADDITIONAL_PARAMETER}
