#!/bin/bash -x

SINGULARITY_IMAGE=$1
MOUNT_DATA=$2
MOUNT_DATA_PROJECT=$3
MONICA_OUT=$4
TMP_DIR=$5
MOUNT_PARAMS=$6
MOUNT_MAS_INFRASTRUCTURE=$7
WORKDIR=$8
SCRIPT=$9
shift 9
ADDITIONAL_PARAMETERS=$@

DATA=/data
OUT=/out
PROJECT=/project
PARAMS=/monica-parameters
MAS_INFRASTRUCTURE=/mas-infrastructure
TMP=/tmp

cd $WORKDIR
echo "set singularity home"
SINGULARITY_HOME=${WORKDIR}
export SINGULARITY_HOME

echo "start python script"

singularity run -H $SINGULARITY_HOME -W $SINGULARITY_HOME -B \
$MOUNT_DATA:$DATA:ro,\
$MOUNT_DATA_PROJECT:$PROJECT:ro,\
$MONICA_OUT:$OUT,\
$TMP_DIR:$TMP,\
$MOUNT_PARAMS:$PARAMS:ro,\
$MOUNT_MAS_INFRASTRUCTURE:$MAS_INFRASTRUCTURE:ro \
${SINGULARITY_IMAGE} python ${SCRIPT} ${ADDITIONAL_PARAMETERS}
