email_server: imap.example.com
port: "993"
mailbox: INBOX
download_path: /some/path
username: username
password: password_better_use_credential
subject: subject
from: from
verbose: true
check_interval: 24